server:
  port: 8888
  
eureka:
  instance:
    hostname: config
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${DISCOVERY_SERVER_PASSWORD:password}@discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brycehan/cloud
          default-label: master
          search-paths: config-repo
  rabbitmq:
    host: rabbitmq
    username: admin
    password: 123456        
  security:
    user:
      name: user
      password: ${CONFIG_SERVER_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh,bus-env'

logging:
  level:
    com.brycehan.cloud: debug
    org.springframework: debug
