server:
  port: 8051
  
spring:
  datasource:
    url: jdbc:h2:mem:user

eureka:
  instance:
    hostname: auth
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123456@discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always      
     
logging:
  level:
    org.springframework: debug
    com.brycehan: debug
        
