server:
  port: 8050

eureka:
  instance:
    hostname: auth
    prefer-ip-address: true
    metadata-map:
      user: user
      password: ${AUTH_SERVER_PASSWORD:password}
  client:
    service-url:
      defaultZone: http://user:123456@discovery:8761/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:user
  rabbitmq:
    host: rabbitmq
    username: admin
    password: 123456
  security:
    user:
      name: user
      password: ${AUTH_SERVER_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always      
 
logging:
  level:
    org.springframework: info
    com.brycehan: debug