server:
  port: ${authserver.port:8050}

eureka:
  instance:
    hostname: auth
    prefer-ip-address: true
    metadata-map:
      user: user
      password: ${AUTH_SERVER_PASSWORD:password}

spring:
  datasource:
    url: jdbc:h2:mem:user
  security:
    user:
      name: user
      password: ${AUTH_SERVER_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always      