server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true

spring:
  zipkin:
    sender:
      type: rabbit
  cloud:
    loadbalancer:
      ribbon:
        enabled: false   
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
#      default-filters:
#      - name: CircuitBreaker
#        args:
#          name: myCircuitBreaker
#          fallbackUri: forward:/  
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: service-a
        uri: lb://service-a
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
      - id: service-b
        uri: lb://service-b
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1