server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${DISCOVERY_SERVER_PASSWORD:password}@discovery:8761/eureka/  

spring:
  cloud:
    gateway:
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: service-a
        uri: lb://service-a
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
      - id: service-b
        uri: lb://service-b
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1