server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://auth:8050/
        predicates:
        - Path=/auth
      - id: service-a
        uri: http://service-a:8060/
        predicates:
        - Path=/a
      - id: service-b
        uri: http://service-b:8070/
        predicates:
        - Path=/b