server:
  port: 8060

eureka:
  instance:
    hostname: service-a
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${DISCOVERY_SERVER_PASSWORD:password}@discovery:8761/eureka/

name: brycehan4

spring:
  rabbitmq:
    host: rabbitmq
    username: admin
    password: 123456
  cloud:
    bus:
      trace:
        enabled: true

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://auth:8050/oauth/token
    resource:
      user-info-uri: http://auth:8050/current

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.brycehan.cloud: debug      
            