server:
  port: 8060

eureka:
  instance:
    hostname: service-a
    prefer-ip-address: true

name: brycehan

spring:
  cloud:
    bus:
      trace:
        enabled: true

security:
  oauth2:
    client:
      client-id: service-a
      client-secret: password
      access-token-uri: http://${authserver.hostname}:${authserver.port}/oauth/token
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}/current

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always  
            