server:
  port: 8070

eureka:
  instance:
    hostname: service-b
    prefer-ip-address: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    circuitbreaker:
      hystrix:
        enabled: false
  zipkin:
    sender:
      type: rabbit
      
security:
  oauth2:
    client:
      client-id: service-b
      client-secret: password
      access-token-uri: http://${authserver.hostname}:${authserver.port}/oauth/token
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}/current

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always   
   