server:
  port: 8071

eureka:
  instance:
    hostname: service-b
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${DISCOVERY_SERVER_PASSWORD:password}@discovery:8761/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: rabbitmq
    username: admin
    password: 123456

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://auth:8050/oauth/token
    resource:
      user-info-uri: http://auth:8050/current

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always   
   