# Tomcat
server:
  port: 9001

# Spring
spring:
  application:
    name: bryce-cloud-auth
  profiles:
    active: dev
  cloud:
    nacos:
      # 服务地址
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}
        group: bryce-cloud
      config:
        namespace: ${spring.profiles.active}
        group: bryce-cloud
  config:
    import:
      - optional:nacos:application-common.yaml
      - optional:nacos:application-cache.yaml
      - optional:nacos:application-endpoint.yaml
      - optional:nacos:application-feign.yaml
      - optional:nacos:application-sentinel.yaml
      - optional:nacos:bryce-cloud-auth.yaml

---
#spring:
#  profiles:
#    active: prod
#  cloud:
#    nacos:
#      # 服务地址
#      server-addr: nacos:8848
