# Tomcat
server:
  port: 9014

# Spring
spring:
  application:
    name: bryce-cloud-monitor
  mvc:
    servlet:
      load-on-startup: 0
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      # 服务地址
      server-addr: @nacos.server-addr@
      discovery:
        namespace: @nacos.namespace@
        group: @nacos.group@
      config:
        namespace: @nacos.namespace@
        group: @nacos.group@
  config:
    import:
      - optional:nacos:application-common.yaml
      - optional:nacos:application-endpoint.yaml
      - optional:nacos:bryce-cloud-monitor.yaml
