# Tomcat
server:
  port: 9014

# Spring
spring:
  application:
    name: bryce-cloud-sms
  cloud:
    nacos:
      # 服务地址
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: bryce-cloud
      config:
        namespace: dev
        group: bryce-cloud
  config:
    import:
      - optional:nacos:application-common.yaml
      - optional:nacos:application-endpoint.yaml
      - optional:nacos:application-sentinel.yaml
      - optional:nacos:application-jwt.yaml
      - optional:nacos:application-cache.yaml
      - optional:nacos:bryce-cloud-sms.yaml
