# Tomcat
server:
  port: 9006

# Spring
spring:
  application:
    name: bryce-cloud-system
  cloud:
    nacos:
      # 服务地址
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: bryce-cloud
      config:
        namespace: dev
        group: bryce-cloud
  config:
    import:
      - optional:nacos:application-common.yaml
      - optional:nacos:application-cache.yaml
      - optional:nacos:application-endpoint.yaml
      - optional:nacos:application-feign.yaml
      - optional:nacos:application-sentinel.yaml
      - optional:nacos:application-common.yaml
      - optional:nacos:application-xxl-job.yaml
      - optional:nacos:application-seata.yaml
      - optional:nacos:application-seata.yaml
      - optional:nacos:application-jwt.yaml
      - optional:nacos:bryce-cloud-system.yaml

seata:
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      namespace: ${spring.cloud.nacos.config.namespace}
      group: SEATA_GROUP
      data-id: seata-server.properties
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      namespace: ${spring.cloud.nacos.discovery.namespace}
      group: SEATA_GROUP
      application: seata-server
