server:
  port: 8761

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true 
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    peer-node-read-timeout-ms: 400
      
spring:
  security:
    user:
      name: user
      password: ${DISCOVERY_SERVER_PASSWORD:password}
    
logging:
  level:
    org.springframework: info
 
    