# Tomcat
server:
  port: 8090

# Spring
spring:
  application:
    name: bryce-cloud-gateway
  cloud:
    nacos:
      # 服务地址
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: bryce-cloud
      config:
        namespace: dev
        group: bryce-cloud
  config:
    import:
      - optional:nacos:application.yaml
      - optional:nacos:bryce-cloud-gateway.yaml
